import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { LocationProvider } from '@/app/components/contexts/LocationContext';
import React from 'react';
import { HouseTypeProvider } from "@/app/components/contexts/HouseTypeContext";
import { RoomProvider } from "@/app/components/contexts/RoomContext";
import { SalesStatusProvider } from "@/app/components/contexts/SalesStatusContext";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AlnairClone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
        >
        <HouseTypeProvider>
          <RoomProvider>
            <SalesStatusProvider>
        <LocationProvider>
          {children}
          </LocationProvider>
            </SalesStatusProvider>
            </RoomProvider>
        </HouseTypeProvider>
        </body>
    </html>
  );
}
